### ISSUE TITLE
Buckaroo push to Magento 2 fails

### ISSUE THREAD

**Issue by miketechtwo** [tig-nl/buckaroo-magento2#1]
Issue Brief
--
When a push from Buckaroo to Magento 2 comes an exceptions occurs.

Environment
--
* PHP Version: (7.0|7.1)
* Magento Version: CE 2.1.6
* Buckaroo Version: v1.3.5
* Magento Deploy Mode: (production|development)

Steps to reproduce
--
1. Install Magento 2.1.6
2. Install Buckaroo Version 1.3.5
3. Buy product and checkout
4. Wait for push from Buckaroo to Magento 2 that transaction is succesfull

---
Actual result
1. Push fails following error occurs:
16-8-2017 09:36:49
push: failed

Tried to update Merchant-webshop with status 190. 
Update was to be sent with POST to: https://www.xxxx.xxx/rest/V1/buckaroo/push 
HTTP statuscode (0 if not available): InternalServerError 
Responsedata: 
Error pushing (https://www.xxxxxxxx/rest/V1/buckaroo/push) : {"message":"Internal Error. Details are available in Magento log file. Report ID: webapi-5993f610e46e6"} 

Push took 0.938 seconds 

Expected result
--
- Push is succesful, status of the order is switched to complete or processing.

Logs
-- 
[2017-08-17 09:10:36] main.CRITICAL: InvalidArgumentException: A stream must either be a resource or a string. in /var/www/m2-clients/xxxx/xxxx.com/build/revision-6f3cb67cd58d8b229daefd53ddcf96ae6b8703d0/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:50
Stack trace:
#0 /var/www/m2-clients/xxxx/xxxx.com/build/revision-6f3cb67cd58d8b229daefd53ddcf96ae6b8703d0/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Monolog\Handler\StreamHandler->__construct(Object(Magento\Framework\ObjectManager\ObjectManager))
#1 /var/www/m2-clients/xxxx/xxxx.com/build/revision-6f3cb67cd58d8b229daefd53ddcf96ae6b8703d0/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Monolog\\Handler...', Array)
#2 /var/www/m2-clients/xxxx/xxxx.com/build/revision-6f3cb67cd58d8b229daefd53ddcf96ae6b8703d0/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Compiled->create('Monolog\\Handler...', Array)
#3 /var/www/m2-clients/xxxx/xxxx.com/build/revision-6f3cb67cd58d8b229daefd53ddcf96ae6b8703d0/vendor/tig/buckaroo/Debug/Debugger.php(303): Magento\Framework\ObjectManager\ObjectManager->create('Monolog\\Handler...', Array)
#4 /var/www/m2-clients/xxxx/xxxx.com/build/revision-6f3cb67cd58d8b229daefd53ddcf96ae6b8703d0/vendor/tig/buckaroo/Debug/Debugger.php(265): TIG\Buckaroo\Debug\Debugger->createStreamHandler('TIG_Buckaroo.lo...')
#5 /var/www/m2-clients/xxxx/xxxx.com/build/revision-6f3cb67cd58d8b229daefd53ddcf96ae6b8703d0/vendor/tig/buckaroo/Model/Push.php(437): TIG\Buckaroo\Debug\Debugger->log()
#6 /var/www/m2-clients/xxxx/xxxx.com/build/revision-6f3cb67cd58d8b229daefd53ddcf96ae6b8703d0/vendor/tig/buckaroo/Model/Push.php(292): TIG\Buckaroo\Model\Push->processFailedPush('canceled', 'Payment failure')
#7 /var/www/m2-clients/xxxx/xxxx.com/build/revision-6f3cb67cd58d8b229daefd53ddcf96ae6b8703d0/vendor/tig/buckaroo/Model/Push.php(244): TIG\Buckaroo\Model\Push->processPush(Array)
#8 [internal function]: TIG\Buckaroo\Model\Push->receivePush()
#9 /var/www/m2-clients/xxxx/xxxx.com/build/revision-6f3cb67cd58d8b229daefd53ddcf96ae6b8703d0/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
#10 /var/www/m2-clients/xxxx/xxxx.com/build/revision-6f3cb67cd58d8b229daefd53ddcf96ae6b8703d0/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#11 /var/www/m2-clients/xxxx/xxxx.com/build/revision-6f3cb67cd58d8b229daefd53ddcf96ae6b8703d0/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#12 /var/www/m2-clients/xxxx/xxxx.com/build/revision-6f3cb67cd58d8b229daefd53ddcf96ae6b8703d0/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /var/www/m2-clients/xxxx/xxxx.com/build/revision-6f3cb67cd58d8b229daefd53ddcf96ae6b8703d0/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#14 /var/www/m2-clients/xxxx/xxxx.com/build/revision-6f3cb67cd58d8b229daefd53ddcf96ae6b8703d0/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#15 {main}

**Comment by tig-jaspersmits** [comment]
Hi Miketechtwo,

I'm unable to reproduce this on a core Magento environment. Could you send an e-mail to servicedesk@tig.nl? Because i would like to take a look at the Magento environment and the error message that shows. If you can include login information for me that would be great.

Jasper

**Comment by Culth** [comment]
Same Issue here.

Magento 2.1.7
Also Module Version 1.3.5

Seems to be someting with the debugger. Have you figured out the issue?

**Comment by tig-robertgrundeken** [comment]
It indeed pin points to the debugger. On the backlog issue [BUCKM2-93](https://jira.tig.nl/projects/BUCKM2/issues/BUCKM2-93) is created. Workaround is to turn off the logger in the configuration. It prevents the error, but is not a solution. 

The actual problem will be solved when this ticket is in the sprint.

**Comment by Culth** [comment]
Thank you!
