### ISSUE TITLE
Checkout agreements

### ISSUE THREAD

**Issue by tdgroot** [tig-nl/buckaroo-magento2#10]
Checkout agreements data isn't submitted when switching payment method and when placing order. Would be great to see this implemented in the future, I had to fix it by myself for now. 

**Buckaroo version**:  1.4.1-alpha
**Magento version**: 2.1.9

**Comment by tig-jaspersmits** [comment]
Hi tdgroot,

Could you show me what you mean exactly by enclosing a screenshot? Do you mean selecting a checkbox in the checkout where you agree to the terms of service?
Because i have my doubts if i understand it correctly.

Kind regards,

Jasper Smits
TIG
