### ISSUE TITLE
PHP 7.1 Support

### ISSUE THREAD

**Issue by peterkoppenaal** [tig-nl/buckaroo-magento2#15]
Hi,

At the moment we are developing a Magento 2.2 shop for one of our clients on PHP 7.1. 
The dependencies/requirements of this module in the composer.json are:

`"php": "~5.5.0|~5.6.0|~7.0.0"`

I forked the repository and changed this requirement to:

`"php": "~5.5.0|~5.6.0|~7.0.0|~7.1.0"`

This seems to work fine. I didn't test the complete module, as I'm expecting TIG to be working on this. 

When will the support for PHP 7.1 added to the module?

thanks in advance!

**Comment by tig-robertgrundeken** [comment]
Hi Peter,

Thank you for your reaction about this matter. Our policy is to support the same PHP version as Magento does. This means Magento 2.1 (5.6.5 or higher, some 7.0's and not 7.1). For Magento 2.2 (some 7.0's and 7.1.x). We currently are in the process of testing it. To keep track on the progress of this issue i created a task: [BUCKM2-170](https://jira.tig.nl/browse/BUCKM2-170)  

kind regards

**Comment by samgranger** [comment]
Are there any updates/eta's regarding this ticket? I see that it's has been placed in a backlog.

**Comment by tungomedia** [comment]
I'm having the same issue. php 7.1 and need the buckaroo plugin. Could someone please clarify when this will be supported?

**Comment by tig-jaspersmits** [comment]
Good afternoon,

We have released an alpha version with PHP 7.1 support. What i would recommend is testing this on your staging/test environment first before you push this to the live environment. You can find the release here: https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.6.1-alpha

If you run into anything please let us know.

kind regards

Jasper
TIG

**Comment by tungomedia** [comment]
Hi Jasper,

Thx for the update. I pulled in the alpha version. so far so good. Shop isn't live yet so no problem. If i run into problems i will let you know.

Thx for the fast update!

**Comment by tig-robertgrundeken** [comment]
@peterkoppenaal @tungomedia @samgranger PHP 7.1 is supported for Magento 2.2.x as of version [v1.6.4 ](https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.6.4)of the Buckaroo Extension. Thank you all for your input!

**Comment by peterkoppenaal** [comment]
@tig-robertgrundeken Thanks!
