### ISSUE TITLE
Some payment methods fail with "Create order before transaction" set to 'No'

### ISSUE THREAD

**Issue by rikwillems** [tig-nl/buckaroo-magento2#18]
When we set config "Create order before transaction" to 'No' we notice that some payment methods fail with the exceptions mentioned below. Failing methods are Creditcard / Sofort / Transfer / Giropay. 
Ideal / Bancontact / Paypal are working correctly with this setting.

main.CRITICAL: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`database`.`sales_order_payment`, CONSTRAINT `SALES_ORDER_PAYMENT_PARENT_ID_SALES_ORDER_ENTITY_ID` FOREIGN KEY (`parent_id`) REFERENCES `sales_order` (`entity_id`) ON DELETE CASCADE) in /vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228

Next Zend_Db_Statement_Exception: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`database`.`sales_order_payment`, CONSTRAINT `SALES_ORDER_PAYMENT_PARENT_ID_SALES_ORDER_ENTITY_ID` FOREIGN KEY (`parent_id`) REFERENCES `sales_order` (`entity_id`) ON DELETE CASCADE), query was: INSERT INTO `sales_order_payment` (`base_shipping_amount`, `shipping_amount`, `base_amount_ordered`, `amount_ordered`, `additional_data`, `cc_exp_month`, `cc_ss_start_year`, `method`, `cc_last_4`, `cc_ss_start_month`, `cc_owner`, `cc_type`, `po_number`, `cc_exp_year`, `cc_ss_issue`, `cc_number_enc`, `additional_information`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) in /vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235

**Comment by tig-jaspersmits** [comment]
Hi Rik,

I just tested this with creditcards, but this does not result in an error. Everything works fine from my side. We can investigate this on your environment if you want. What i would recommend is contacting Buckaroo about this. They will try to solve the problem with you, if they are unable to provide a solution they will forward the issue to us.

You can contact Buckaroo on support@buckaroo.nl or call them on phone number 030-711 5000.

Kind regards,

Jasper
TIG
