### ISSUE TITLE
Cancelling/ rejecting an order makes checkout unusable M2 2.2.2/buckaroo 1.5.4-alpha

### ISSUE THREAD

**Issue by acohin** [tig-nl/buckaroo-magento2#19]
Hi!

- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento extension.

- [x] Bug report (encountered problems with the TIG Buckaroo Magento extension)

---

Cancelling an order when using the iDEAL module renders the checkout module (both shopping cart and checkout) unusable, caused by the following exception:
```
 PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Quote\Model\Cart\Totals::setExtensionAttributes() must be an instance of Magento\Quote\Api\Data\TotalsExtensionInterface, instance of Magento\Quote\Api\Data\AddressExtension given, called in /var/www/vhosts/ltc/web/shop/vendor/magento/framework/Api/DataObjectHelper.php on line 125 and defined in /var/www/vhosts/ltc/web/shop/vendor/magento/module-quote/Model/Cart/Totals.php:592
```

Steps to reproduce in a blank M2 2.2.2 installation:

- Ensure you have product data, either by creating a product or by using sample data. I installed Magento using the following command:
```
mr2 setup:install --base-url=<url> \
--db-host=localhost --db-name=test --db-user=root --db-password=<pwd> \
--admin-firstname=Test --admin-lastname=User --admin-email=<email> \
--admin-user=admin --admin-password=<pwd> --language=en_US --currency=EUR \
--timezone=Europe/Amsterdam --use-rewrites=1 --backend-frontname=admin --use-sample-data
```
- composer require tig/buckaroo. This requires you to set minimun-stability = alpha and prefer-stable = true
- I'm using production mode, so run setup:upgrade, setup:di:compile and setup:static-content:deploy
- Setup buckaroo payment module with test account data, and enable the iDEAL module (Test)
- Order a single product (our shop is only populated by configurable products, but it shouldn't matter) and checkout as guest using the Buckaroo iDEAL module.
- Select 890 - Cancelled by user.

You should now end up back on the _checkout/cart_ page with a single line of text - Estimate Shipping and Tax, caused by the above mentioned exception. 
- Rejecting the order gives the same result, didn't try the other failure states. 
- Success works as intended and doesn't cause any errors.
- I haven't tested any of the other payment methods.

The issue does not occur when using the stable 1.5.3 version, however this version is locked to Magento 2.2.1 -- 2.2.2 introduces several bugfixes which are crucial to our projects.

Regards,

Arno
Muntz

**Comment by tig-jaspersmits** [comment]
Hi Arno,

Thank you for informing us about this. We will release version 1.6.0 of the extension today. The problem you mentioned has been fixed in this release. I would recommend keeping an eye on our Buckaroo Extension page: https://tig.nl/buckaroo-magento2-open-source-extensie/

Once this version has been released you can update the extension and everything should work as intended.

Kind regards,

Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi Arno,

As a side-note, this is caused by the core Magento bug mentioned here: https://github.com/magento/magento2/issues/12993

Kind regards,

Jasper
TIG

**Comment by acohin** [comment]
Hi Jasper,

I've updated to the new 1.6.0 version and indeed the problem appears to be fixed now.

Thanks!

Arno
Muntz

**Comment by tig-jaspersmits** [comment]
Hi Arno,

Great to hear!
No problem.

Jasper
TIG
