### ISSUE TITLE
Available credit cards in sub store not working correctly

### ISSUE THREAD

**Issue by arnoudhgz** [tig-nl/buckaroo-magento2#25]
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento extension.

---

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with the TIG Buckaroo Magento extension)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When I set the available credit cards in my default config to e.g. only American Express and in a specific store view to e.g. American Express, Mastercard and Visa only American Express will appear in the checkout. 

Expected result is that when I have multiple store views with mostly the same credit cards, but I want a special configuration in one or more store views I can alter the credit cards for those specific store views (and see this alteration in the checkout).

### TIG supportdesk

On Github we will respond in English even when the question was asked in Dutch.

**Comment by tig-jaspersmits** [comment]
Hi Arnoudhgz,

Thank you for informing us about this. We have just confirmed the problem and created a backlog issue: https://jira.tig.nl/browse/BUCKM2-224

We would like to recommend to keep an eye on the status of that issue. If you have any further questions please let me know.

Kind regards,

Jasper
TIG

**Comment by tig-robertgrundeken** [comment]
Hi @arnoudhgz 
Thanks for your input! This is fixed in [v1.7.0](https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.7.0)
