### ISSUE TITLE
Status color (grey / yellow / green) not corresponding with store configuration

### ISSUE THREAD

**Issue by arnoudhgz** [tig-nl/buckaroo-magento2#26]
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento extension.

---

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with the TIG Buckaroo Magento extension)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When I disable a payment method in the default config a grey marker shows at the payment method (which is correct). But when I enable (test / live) this on a specific store view this marker stays at the same color as the one from the default configuration.

This makes it hard to quickly see in the specific store view which payment methods are enabled/disabled. You can't really rely on the color you see, you have to open/close each payment method on the store view to be sure.

This issue occurs for every combination of status in the default config and the store specific config. In other words not only default disabled, store enabled, also e.g. default test, store live.

### TIG supportdesk

On Github we will respond in English even when the question was asked in Dutch.

**Comment by tig-jaspersmits** [comment]
Hi Arnoudhgz,

Thank you for informing us about this. We have just confirmed the problem and created a backlog issue: https://jira.tig.nl/browse/BUCKM2-225

We would like to recommend to keep an eye on the status of that issue. If you have any further questions please let me know.

Kind regards,

Jasper
TIG

**Comment by tig-robertgrundeken** [comment]
Hi @arnoudhgz 
Thanks for your input! This is fixed in [v1.7.0](https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.7.0)
