### ISSUE TITLE
Print page of order is broken

### ISSUE THREAD

**Issue by jasperzeinstra** [tig-nl/buckaroo-magento2#27]
### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento extension.

---

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with the TIG Buckaroo Magento extension)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

The `Sales Order Print` page is broken. It's showing the Ordered Items block twice, once with a list of products and once without. It showing the Invoice and Shipping address, Shipping method and Payment method twice. 

This is because `view/frontend/layout/sales_order_print.xml` of the Buckaroo extension aren't working together with the default Magento layout. The file of the buckaroo extension want to overwrite the `order_totals` block and use its own class and template. Best thing to do is only overwrite this block.

```<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="order_items">
            <block class="TIG\Buckaroo\Block\Order\TotalsFee" name="order_totals" template="TIG_Buckaroo::sales/order/totals.phtml">
                <arguments>
                    <argument name="label_properties" xsi:type="string">colspan="4" class="mark"</argument>
                    <argument name="value_properties" xsi:type="string">class="amount"</argument>
                </arguments>
            </block>
        </referenceBlock>
    </body>
</page>
```

**Comment by tig-jaspersmits** [comment]
Hi Jasper,

Thank you for your submission. Just tried to reproduce and i see that this is shown twice when i print the order. Just created a backlog item for this which you are able to see when you login on this page: https://public.tig.nl/

Kind regards,

Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi Jasper,
Sorry for this very delayed reaction, but this problem has been solved.

Kind regards,

Jasper
TIG
