### ISSUE TITLE
Critital error log

### ISSUE THREAD

**Issue by hypershopbv** [tig-nl/buckaroo-magento2#29]
The system log throws an error on checking out:

CRITICAL: Invalid template file: 'Magento_Payment::info/pdf/default.phtml' in module: 'TIG_Buckaroo' block's name: 'info_1'

**Comment by tig-jaspersmits** [comment]
Good afternoon,

Thank you for your message. Please provide us with more information by sending us an e-mail on sd@tig.nl. We are unaware of any problems in the checkout so this might be a Magento environment or extension conflict problem.

Kind regards,

Jasper
TIG
