### ISSUE TITLE
Magento 2.1.9 is out, but incompatible as defined by composer.json

### ISSUE THREAD

**Issue by linden2015** [tig-nl/buckaroo-magento2#3]
Magento 2.1.9

* http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.9CE.html

This repository's composer.json:

    "magento/framework": ">=100.0.10,<=100.0.17|>=100.1.0,<=100.1.8"

When trying to install together:

    Your requirements could not be resolved to an installable set of packages.

Will a pull request be accepted that raises the version? How can this be resolved?

**Comment by tig-robertgrundeken** [comment]
Hi Linden2015,

I added your request as item on the backlog: [BUCKM2-102](https://jira.tig.nl/projects/BUCKM2/issues/BUCKM2-102). We and Buckaroo already had contact about this matter last week, and we understand it and we will put it as soon as possible on the sprint planning.

A little bit background information: 
The policy TIG and Buckaroo agreed on is to not support versions (via composer) without fully test them first ourselves. This to prevent the merchant to switch to a new version of magento and find out possible problems when fully installed. This is based on the experience in the past were there where also in patch updates changes in the checkout process. 

Thank you for taking the time to letting us know.

**Comment by tig-robertgrundeken** [comment]
Hi Linden2015,

We slightly changed our policy. 
Shortly after a new release of Magento, we will release an alpha version of the Buckaroo extension supporting the latest version. We have not fully tested this version.

For Magento 2.1.9 we just created this version:
https://github.com/tig-nl/buckaroo-magento2/tree/v1.4.1-alpha

Meanwhile we are testing it for Magento 2.1.9. And when all good make a stable release.

regards

**Comment by martijnrmediact** [comment]
We still havent received feedback on the alpha release. We have clients waiting for this. Please let us know if this can be installed and deployed on live.

**Comment by tig-robertgrundeken** [comment]
Hi Martijn,

I switched the status of the issue: [BUCKM2-102](https://jira.tig.nl/browse/BUCKM2-102) to in progress. The test results and our advise are handed over to Buckaroo, and they have to decide on the next step (like fixes for known bugs).

On the question "can this be installed and deployed on live". Technically you can. If you are asking where lay the responsibilities when installing an alpha: it is at your own risk.

**Comment by tig-robertgrundeken** [comment]
Hi,
We just released the stable version [v1.5.1](https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.5.1) with support for Magento 2.1.9.
