### ISSUE TITLE
Tax information is missing in My Account on orders/invoiced totals when Buckaroo module is activated

### ISSUE THREAD

**Issue by esseremmerik** [tig-nl/buckaroo-magento2#31]
---

### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento extension.

---

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with the TIG Buckaroo Magento extension)
---

### Description of your *issue*, suggested solution and other information

When the Buckaroo module is enabled, the tax information is missing in the totals section of the order/invoice history of the customer my account section. Reproduced it by temporary disabling the Buckaroo module, open the order/invoice history to see it is displayed and then enable it again to see it is missing. Maybe something to do with adding the new "Fee" section and so replacing some XML definitions for the tax section?

### TIG supportdesk

On Github we will respond in English even when the question was asked in Dutch.

**Comment by tig-jeffreypeeters** [comment]
Hey @esseremmerik,

I've managed to reproduce your problem and I've created a item for you on our backlog. We'll be investigating this issue further and when we know more I'll let you know.

Kind regards,
Jeffrey Peeters

TIG

**Comment by tig-jeffreypeeters** [comment]
Hey @esseremmerik ,

One of our developers has found the problem and is working on a fix. You can probably expect this fix in either the upcoming or the next release but I'll let you know when we know more.

Kind regards,
Jeffrey Peeters

TIG

**Comment by GerbenHoes** [comment]
Hi,
Can you please indicate when this will be put live?
Kind regards,
Gerben

**Comment by tig-jeffreypeeters** [comment]
Hey @GerbenHoes,

We don’t have an exact date yet but we’re expecting Buckaroo 1.7.3 to go live mid-october. That release will contain the fix for this issue.

Kind regards,
Jeffrey Peeters

TIG

**Comment by tig-robertgrundeken** [comment]
@esseremmerik  I made [v1.7.4-RC1](https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.7.4-RC1) available with the fix. Still RC though.

**Comment by esseremmerik** [comment]
Confirmed the fix in 1.7.4-RC1

**Comment by tig-jaspersmits** [comment]
Hi @esseremmerik,

Great to hear!
Hereby i will close the Github issue.

Kind regards,

Jasper
TIG
