### ISSUE TITLE
Creditmemo push causes error

### ISSUE THREAD

**Issue by esseremmerik** [tig-nl/buckaroo-magento2#34]
- [X] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento extension.

- [X] Bug report (encountered problems with the TIG Buckaroo Magento extension)
---

### Description of your *issue*, suggested solution and other information

In error logs (New Relic) we see structural errors on a refund push. (occurred at least 7 times last week)

This is the error log:

URL: /Webapi/Rest/TIG\Buckaroo\Api\PushInterface/receivePush

**TypeError:** Uncaught exception 'TypeError' with message 'Argument 2 passed to Magento\Sales\Model\Order\CreditmemoFactory::getQtyToRefund() must be of the type array, string given, called in /vendor/magento/module-sales/Model/Order/CreditmemoFactory.php on line 77' in /vendor/magento/module-sales/Model/Order/CreditmemoFactory.php:290

I suspect the creditmemo creation will fail as well, but I cannot relate te error to a specific order so I was unable to check the impact.

### TIG supportdesk

On Github we will respond in English even when the question was asked in Dutch.

**Comment by tig-jaspersmits** [comment]
Good morning,

Thank you for submitting this. I will discuss this with my colleague. But in the TypeError i see nothing related to Buckaroo. Everything points to core Magento related files. Once i've discussed this with my colleague i will let you know.

Kind regards,

Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Good morning,

Just discussed this. There should be more information in the error log. Could you provide me with the full error log? Maybe it's easier to send me an mail on sd@tig.nl with this information. Since this problem is unknown, we might need Magento login information to investigate this further.

Kind regards,

Jasper
TIG

**Comment by tig-robertgrundeken** [comment]
@esseremmerik I made [v1.7.4-RC1](https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.7.4-RC1) available with all the fix. It is not extensively tested thats why it is still in RC.

**Comment by tig-robertgrundeken** [comment]
We added it in v1.8.0:
https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.8.0
