### ISSUE TITLE
Support for Magento 2.2.6 and 2.1.15

### ISSUE THREAD

**Issue by igorwulff** [tig-nl/buckaroo-magento2#35]
- [X] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with the TIG Buckaroo Magento extension)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [X] Other

---

### Description of your *issue*, suggested solution and other information

Magento released a critical security update for Magento 2.2.6 and 2.1.15. Can you create a new release and at least a RC for this as soon as possible?

**Comment by tig-robertgrundeken** [comment]
We are working on it.. hoping to release a RC within the next hour..

**Comment by tig-robertgrundeken** [comment]
Here it is: https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.7.3-RC1

**Comment by peterjaap** [comment]
@tig-robertgrundeken could you click 'Update' on the Packagist page? The 1.7.3-RC1 does not show there. https://packagist.org/packages/tig/buckaroo

**Comment by tig-robertgrundeken** [comment]
@peterjaap @igorwulff the version in the composer.json did not have the RC1 so the packagist webhook did not work. We changed that + while changing the file added php 7.2 for testing purposes.

**Comment by peterkoppenaal** [comment]
What is the expected date for 1.7.3 to be released?
