### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by peterjaap** [tig-nl/buckaroo-magento2#36]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with the TIG Buckaroo Magento extension)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

All current versions of this extension have this restraint; `"php": "~5.5.0|~5.6.0|~7.0.0|~7.1.0",`.

In preparation of Magento 2.3 (which will need at least PHP 7.1), we are moving our shops towards PHP 7.2. This extension is one of the extensions that prevents us from doing so at this point in time. Do you have any idea when this extension will be PHP 7.2 compatible (or maybe it is, but it hasn't been tested yet)?

**Comment by tig-robertgrundeken** [comment]
@peterjaap after reading this and fixing version v1.7.3-RC1 for packagist.org, we added ~7.2.0 to the php restraint for testing purposes.

**Comment by wouter-toppershops** [comment]
@tig-robertgrundeken 

i try to install the module with PHP `7.2.10` and also on Magento `2.3` it said the `magento/framework` requires `7.0.2|7.0.4|~7.0.6|~7.1.0`  could you please also update the magento framework. to `>=102.0.0` 

and the `magento/payment` to `>=100.3.0`

**Comment by wouter-toppershops** [comment]
@tig-robertgrundeken any idea when this is solved?

i cant install version 1.7.4-RC1 ether because its still has the framework requirement not set correctly.

**Comment by wouter-toppershops** [comment]
See Pull: https://github.com/tig-nl/buckaroo-magento2/pull/40
