### ISSUE TITLE
Unable to install / update with composer

### ISSUE THREAD

**Issue by Naberdz** [tig-nl/buckaroo-magento2#37]
### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with the TIG Buckaroo Magento extension)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information
Unable yo install / update extension getting the following error on composer update / require 
Composer\Downloader\TransportException]                                                                                                                   
  The "https://buckaroomagento2.tig.nl/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known  
  failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by tig-jaspersmits** [comment]
Good afternoon,

Unfortunate to hear that you are experiencing this problem. What way are you trying to install the extension? Did you follow the steps in the installation manual?: https://confluence.tig.nl/x/bwLj

Kind regards,

Jasper
TIG

**Comment by Naberdz** [comment]
i'm trying to install it with composer. by following this guide:
https://confluence.tig.nl/display/SDBUCKAROO/EN+%7C+Installation+with+Composer

Op vr 19 okt. 2018 om 12:37 schreef Jasper Smits <notifications@github.com>:

**Comment by tig-robertgrundeken** [comment]
@Naberdz 
https://buckaroomagento2.tig.nl/packages.json is the old location. You should try to set it up linking to this github or packagist.
