### ISSUE TITLE
Theme name in body class

### ISSUE THREAD

**Issue by tdgroot** [tig-nl/buckaroo-magento2#38]
### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento 2 extension.

---

### What is the purpose of your *issue*?
- [x] Other

---

What's the point of the block `TIG\Buckaroo\Block\Frontend\ThemeBodyClass` being added to layout? It adds the current theme name to the body class, but how is the theme name relevant to Buckaroo?

**Comment by tig-bartrusschenberg** [comment]
Hi @tdgroot
 
Magento has by default two themes (Blank and Luma) in which the styling of form fields differ from each other. We add the theme body class to make the styling of some elements within the Buckaroo extension compatible with the frontend (either Luma or Blank). 

Kind regards,
Bart
