### ISSUE TITLE
Support for multi-language stores

### ISSUE THREAD

**Issue by rikwillems** [tig-nl/buckaroo-magento2#4]
The Buckaroo module sends the customer to a Dutch version of the interface. This doesn't work for multi-language webshops. Can the Culture setting in the TransactionBuilder be set by the current store view languange?

**Comment by tig-jaspersmits** [comment]
Hi Rik,

Do you mean the payment page of Buckaroo when the customer switches from the Magento shop to the payment platform? If you could send me an e-mail on servicedesk@tig.nl with a screenshot of this problem then it might be a little easier for me to look into it.

Kind regards,

Jasper

**Comment by rikwillems** [comment]
Hi Jasper,

Yes that is what I mean. We have a client with an English webshop. We had to change the Culture inside the extension to get customers into an English payment screen. This Culture is hard set and not through store settings.

**Comment by tig-jaspersmits** [comment]
Hi Rik,

I just confirmed this and created a backlog item so we can fix this in a future update. This project is public so you can monitor the status here: https://jira.tig.nl/browse/BUCK2L-20

Feel free to contact me if you have any further questions.

Kind regards,

Jasper

**Comment by tig-jaspersmits** [comment]
p.s. this is the correct link: https://jira.tig.nl/browse/BUCKM2-106
