### ISSUE TITLE
Magento 2.3 support

### ISSUE THREAD

**Issue by esseremmerik** [tig-nl/buckaroo-magento2#42]
### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento 2 extension.

---

### What is the purpose of your *issue*?
- [X] Other

---

### If the purpose of your issue is a *feature request*
Magento is releasing 2.3 this week on Wednesday (28th november), what is your schedule for a 2.3 support release as I cannot find activity in this repo for this. 2.3 contains a lot of important fixes and improvements, so we want to update a.s.a.p.

### TIG support

- Please ask your question in English to ensure that your issue can help other people internationally. Nevertheless we will respond in English.

**Comment by tig-robertgrundeken** [comment]
@esseremmerik Buckaroo agreed to do first a release with lots of improvements however this is not the version which supports Magento 2.3. We are working on that on the side see #40 . Supporting Magento 2.3 will be the next step after this release.

**Comment by tig-robertgrundeken** [comment]
@esseremmerik there is now a RC1 version: https://github.com/tig-nl/buckaroo-magento2/releases/tag/v2.0.0-RC1
