### ISSUE TITLE
Orders with pending Sofort payment get cancelled

### ISSUE THREAD

**Issue by pauluse** [tig-nl/buckaroo-magento2#45]
### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento 2 extension.

---

### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)
- [ ] Bug report (encountered problems with the TIG Buckaroo Magento 2 extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If the purpose of your issue is a *feature request*
- As a *customer using Sofort banking* I’d like *my order not to be cancelled* in order to *receive my product*. Right now my order gets cancelled even though my payment was successful.
- Suggestions and background: 
  Sofort payments can take a while before the payment is accepted in Buckaroo. In our case it took almost 27 hours before the transaction changes from processing to success in Buckaroo. Within this timeframe the default Magento cron has cancelled the order because it exceeded the "Pending Payment Order Lifetime" value in "Configuration > Sales > Sales > Orders Cron Settings". In this cron we would like to see Sofort payments (and maybe other methods which can take quite a while to process) to be ignored.

**Comment by tig-jaspersmits** [comment]
Hi @pauluse,

Thank you for submitting this. Just created a backlog issue for this. It might take some time before this will be implemented because it is up to Buckaroo to decide when and what they want in the extension. If you want i can put you on our release notes mailing list. Let me know if you want that (and include your mail address) so i can add this.

Kind regards,

Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @pauluse,

By default, Buckaroo Sofortpayments are only set to success when the money is received by Buckaroo. However, Buckaroo can also ensure that this happens immediately when the payment is directly confirmed by the consumer. This is a setting that Buckaroo can change. You can contact Buckaroo support on support@buckaroo.nl or call Buckaroo on phone number 030-711 5000 to have this setting changed.

Kind regards,

Jasper
TIG
