### ISSUE TITLE
Support for Magento 2.2.7

### ISSUE THREAD

**Issue by igorwulff** [tig-nl/buckaroo-magento2#49]
- [X] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with the TIG Buckaroo Magento extension)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [X] Other

---

### Description of your *issue*, suggested solution and other information

Magento released a update for Magento 2.2.7. Can you create a new release and at least a RC for this as soon as possible?

**Comment by joost-florijn-kega** [comment]
In Magento 2.2.7 are several high risk security issues fixed and i would like to update to that version but Buckaroo prevents me from updating to Magento 2.2.7.

**Comment by tig-robertgrundeken** [comment]
Thanks for creating this issues: V1.8.0 supports 2.1.16 and 2.2.7! 
https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.8.0
