### ISSUE TITLE
Not able to create creditmemo programmatically when Buckaroo refund option  is enabled

### ISSUE THREAD

**Issue by gigadesign1** [tig-nl/buckaroo-magento2#52]
### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento 2 extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [X] Bug report (encountered problems with the TIG Buckaroo Magento 2 extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
- Create a creditmemo programmatically with the refund option of the Buckaroo module enabled
- The value of the creditmemo is refunded through Buckaroo plaza
- Error message:  Notice: Undefined index: creditmemo in /vendor/tig/buckaroo/Model/Method/AbstractMethod.php on line 1157
- None

Problem is that the function in this line depends on a value from the request, which obviously is not set when a creditmemo is created programmatically through a cronjob. Is it possible to change this to an observer of some kind so we can automate the refunding process of our returns?

**Comment by tig-jeffreybranderhorst** [comment]
Hello @gigadesign1,

Thank you for submitting this. Just created a backlog issue for this. It might take some time before this will be implemented because it is up to Buckaroo to decide when and what they want in the extension. If you want I can put you on our release notes mailing list. Let me know if you want that (and include your mail address) so I can add this.

Kind regards,
Jeffrey - TIG

**Comment by tig-jaspersmits** [comment]
Updating the extension should solve this problem.
Hereby I close the Github issue.

**Comment by gigadesign1** [comment]
Hi @tig-jaspersmits,

I have already contacted support, but it looks like the feature is removed in the newest version of the module ?

Can you point me to where the module sends a refund request to Buckaroo when a creditmemo is created in Magento?
I can't find any event or plugin that does that, and nothing happens if we test this feature.
