### ISSUE TITLE
Afterpay digiaccept does not work with bundled product

### ISSUE THREAD

**Issue by pollyrobin** [tig-nl/buckaroo-magento2#54]
### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento 2 extension.

~~Not verified, I am running TIG Buckaroo Magento 2 version 1.7.3 I looked through the relevant commits until the latest version and i can't see anything that would fix this bug, so i expect this bug to still be in the latest version (can't verify this easily)~~
Upgraded to 1.8.1 same issue, can't upgrade to 2.0.0 since we use magento 2.2.6

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [X] Bug report (encountered problems with the TIG Buckaroo Magento 2 extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
- Step 1, Step 2, ...
- Expected result
- Actual result (Please provide screenshots if applicable)
- Workaround (If available, otherwise just write "None")

We are currently using the after pay method digiaccept.
Every order with an bundled product will fail. we will get the message Total amount of articles does not match the transaction amount.
This is because the module does not send the bundled product as part of the order. 

The relevant code can be found in [https://github.com/tig-nl/buckaroo-magento2/blob/master/Model/Method/Afterpay.php](url)

The bug seems to be in the getRequestArticlesData method.

```
foreach ($cartData as $item) {
            // Child objects of configurable products should not be requested because afterpay will fail on unit prices.
            if (empty($item)
                || $this->calculateProductPrice($item, $includesTax) == 0
                || $item->getProductType() == Type::TYPE_BUNDLE
            ) {
                continue;
            }
            $article = $this->getArticleArrayLine(
                $count,
                $item->getQty() . ' x ' . $item->getName(),
                $item->getProductId(),
                1,
                $this->calculateProductPrice($item, $includesTax),
                $this->getTaxCategory($item->getTaxClassId(), $payment->getOrder()->getStore())
            );
```

The important part is line number 657: 
```
|| $item->getProductType() == Type::TYPE_BUNDLE
```
As long as this line is in the code it will never create an article to send to Buckaroo.

This line has been added in commit: https://github.com/tig-nl/buckaroo-magento2/commit/8a036bfc805550765c3046ae63077f32c4892bdf#diff-2fe9c7dcfdda9f8ebef112c0d0410b1c

The commit message is Bundled products can now be paid with Afterpay
But for me it has the opposite effect. 

If i remove the line the bundled product gets added perfectly fine and the order proceeds normally.

Buckaroo result:
      <ns1:AmountDebit>31.85</ns1:AmountDebit>
     <ns1:Services>
         <ns1:RequestParameter Name="ArticleDescription" GroupID="1">Servicekosten</ns1:RequestParameter>
          <ns1:RequestParameter Name="ArticleId" GroupID="1">1</ns1:RequestParameter>
          <ns1:RequestParameter Name="ArticleQuantity" GroupID="1">1</ns1:RequestParameter>
          <ns1:RequestParameter Name="ArticleUnitPrice" GroupID="1">0.95</ns1:RequestParameter>
          <ns1:RequestParameter Name="ArticleVatCategory" GroupID="1">1</ns1:RequestParameter>
          <ns1:RequestParameter Name="ShippingCosts">3.95</ns1:RequestParameter>
        </ns1:Service>

Buckaroo expected result 
      <ns1:AmountDebit>31.85</ns1:AmountDebit>
      <ns1:Services>
        <ns1:Service Name="afterpaydigiaccept" Action="Pay" Version="1">

          <ns1:RequestParameter Name="ArticleDescription" GroupID="1">1 x Paarden Verjaardag Pakket</ns1:RequestParameter>
          <ns1:RequestParameter Name="ArticleId" GroupID="1">59502</ns1:RequestParameter>
          <ns1:RequestParameter Name="ArticleQuantity" GroupID="1">1</ns1:RequestParameter>
          <ns1:RequestParameter Name="ArticleUnitPrice" GroupID="1">26.95</ns1:RequestParameter>
          <ns1:RequestParameter Name="ArticleVatCategory" GroupID="1">1</ns1:RequestParameter>
          <ns1:RequestParameter Name="ArticleDescription" GroupID="2">Servicekosten</ns1:RequestParameter>
          <ns1:RequestParameter Name="ArticleId" GroupID="2">1</ns1:RequestParameter>
          <ns1:RequestParameter Name="ArticleQuantity" GroupID="2">1</ns1:RequestParameter>
          <ns1:RequestParameter Name="ArticleUnitPrice" GroupID="2">0.95</ns1:RequestParameter>
          <ns1:RequestParameter Name="ArticleVatCategory" GroupID="2">1</ns1:RequestParameter>
          <ns1:RequestParameter Name="ShippingCosts">3.95</ns1:RequestParameter>
        </ns1:Service>

**Comment by tig-robertgrundeken** [comment]
@pollyrobin thanks for de detailed and clear description. We will test it locally to reproduce it and put it on the backlog.

I remember adding the line of code:
`|| $item->getProductType() == Type::TYPE_BUNDLE`

Because Magento did sum up first all the products separately and after that also had the bundle in the items. We will look into this.

**Comment by tig-jaspersmits** [comment]
Hi @pollyrobin is it possible to get to your test environment and take a look at the settings for the bundled product? If so, could you maybe mail the credentials to support@tig.nl?

I tried to reproduce your problem, but I run into something else and not the same problem you are experiencing.

Looking forward to your response.

**Comment by tig-jaspersmits** [comment]
@pollyrobin is it correct that you have "Dynamic Price" disabled for these bundled products?
