### ISSUE TITLE
Signature check fails on certain account names

### ISSUE THREAD

**Issue by pauluse** [tig-nl/buckaroo-magento2#55]
### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento 2 extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG Buckaroo Magento 2 extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
In some cases the `\TIG\Buckaroo\Model\Validator\Push::calculateSignature` method calculates an incorrect hash due to decode issues. The `$this->originalPostData` which is logged shows a value like `JOHN + DOE INCORPORATION` for the key `brq_SERVICE_transfer_CustomerAccountName`. In `\TIG\Buckaroo\Model\Validator\Push::decodePushValue` this value gets processed by `urldecode` which converts the + sign into a space. This results in an incorrect signature calculation which makes the push fail.

- **Expected result**
I expect the push to be processed

- **Actual result (Please provide screenshots if applicable)**
The push fails with `Invalid push signature`

- **Workaround (If available, otherwise just write "None")**
I have added `brq_SERVICE_transfer_CustomerAccountName` to the switch-case in `\TIG\Buckaroo\Model\Validator\Push::decodePushValue`, this seems to have no impact on further pushes, especially seems this data posted by Buckaroo doesn't seem to be encoded in first place.

**Comment by pauluse** [comment]
In #56 @tig-robertgrundeken mentioned this issues should be fixed in v1.9.0
We are currently on 1.9.2 for our customer and we just had the exact same issue again.

So for now this still seems to be an serious issue for customers with a `+` in their account name

**Comment by tig-robertgrundeken** [comment]
Hi @pauluse sorry for the inconvenience. We had to revoke this change because of problems in live mode (as stated by [v1.9.1](https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.9.1)). 

In short, there is no generic solution for this. We get an encode url from the Push where "+"-signs are spaces, but the actual "+" are kept and not encoded. Simply adding the parameter to the list of not decoded values can create errors for other users.

Can we help you with this issue in other ways that you can solve this for your user?

**Comment by tig-jaspersmits** [comment]
Because of a clean-up action we will close this ticket.
