### ISSUE TITLE
Magento 2.3.1/2.2.8 support

### ISSUE THREAD

**Issue by tig-dennisvanderhammen** [tig-nl/buckaroo-magento2#58]
## Please follow the guide below

- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like.
- We may ask some questions or ask you to provide addition information after you placed your request.

---

### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento extension.

---

### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)
- [ ] Bug report (encountered problems with the TIG Buckaroo Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If the purpose of your issue is a *feature request*
- As a merchant or developer I’d like to be able to update to Magento 2.3.1 with the Buckaroo extension installed in order to stay up-to-date with the latest Security patches.

### TIG support

- Please ask your question in English to ensure that your issue can help other people internationally. Nevertheless we will respond in English.

**Comment by FreekVandeursen** [comment]
Is there already an expected timeline for supporting the latest Magento versions?

**Comment by tig-jaspersmits** [comment]
You will see an update in this Github issue once there is a support for those versions. No timeline available at this point.

**Comment by ginos87** [comment]
We are working on a project with Magento 2.1 at work and it would be nice if 2.1.17 would also be supported by the TIG Buckaroo Magento extension

**Comment by rickschippers** [comment]
> We are working on a project with Magento 2.1 at work and it would be nice if 2.1.17 would also be supported by the TIG Buckaroo Magento extension

You should also be looking at upgrading that installation soon. Magento support for 2.1 will end in June 2019.

**Comment by tig-jaspersmits** [comment]
Version 1.9.2 has been released with support for Magento 2.3.1 and 2.2.8.
