### ISSUE TITLE
Paypal Payment from Specific Country multiple select does not work

### ISSUE THREAD

**Issue by Timothy-V** [tig-nl/buckaroo-magento2#59]
### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento 2 extension.

Magento Open Source: v2.3.1
TIG/Buckaroo: v1.9.2

Bug was already reported to Buckaroo when we were still on Magento 2.2.5 with TIG buckaroo 1.7.2.
---
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with the TIG Buckaroo Magento 2 extension)
---
### If your issue contains security sensitive information
** If your issue may contain sensitive information, please send us an e-mail at security@tig.nl.**
- [x ] This issue does not contain any security sensitive information
---

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
- Step 1, Step 2, ...
Configuration->Payment Methods->Configure Buckaroo->Paypal->Advanced config->Payment from Specific Country->Perform a multiple select on a few countries-> Save settings.
![image](https://user-images.githubusercontent.com/47175711/56287736-75371200-611d-11e9-993b-7067fc9ddd18.png)

- Expected result
At the checkout the Paypal payment method disappears when a customer selects any other country then set in the Payment from Specific Country.

- Actual result (Please provide screenshots if applicable)
Paypal keeps showing, no matter what country you choose.
![image](https://user-images.githubusercontent.com/47175711/56288732-a9133700-611f-11e9-9de6-9f37b87efb4b.png)
![image](https://user-images.githubusercontent.com/47175711/56288743-afa1ae80-611f-11e9-967f-8306875e6b5a.png)

- Workaround (If available, otherwise just write "None")
None. You can select only one country as specific, then it works correctly. But this field makes multiple select possible, it's not a dropdown. So it should support multiple select correctly.

**Comment by tig-jaspersmits** [comment]
Hi @Timothy-V ,

I responded on the message you've sent to our Servicedesk.
So far I have been unable to reproduce this.

Kind regards,

Jasper

**Comment by Timothy-V** [comment]
Hi @tig-jaspersmits ,
Did you select multiple countries as I stated in Step1, Step2... ?
Or did you just select a single country. Cause the issue only occurs with multiple select.

**Comment by tig-jaspersmits** [comment]
Multiple countries selected.
https://www.screencast.com/t/L6prtf7I89ud
https://www.screencast.com/t/rPWpLMlyEY

**Comment by Timothy-V** [comment]
Did some further testing.

Settings:
![image](https://user-images.githubusercontent.com/47175711/56651724-006a5780-668a-11e9-8f5a-fede21fde5aa.png)

Checkout situation 1:
![image](https://user-images.githubusercontent.com/47175711/56651688-edf01e00-6689-11e9-9bd2-fb14b6a7df46.png)

Checkout situation 2:
![image](https://user-images.githubusercontent.com/47175711/56651932-6951cf80-668a-11e9-9df6-8bfa3ad7aa4d.png)

Conclusion:
It's a Mageplaza - One Step Checkout issue?

**Comment by Timothy-V** [comment]
I contacted Mageplaza and they provided a patch for the following file:

/magento2/app/code/Mageplaza/Osc/view/frontend/web/js/model/shipping-rates-validator.js 

Problem is solved now.

**Comment by tig-jaspersmits** [comment]
Hi @Timothy-V ,

Good to hear! I will also share it on our knowledge base.
Thanks for letting me know.

Kind regards,

Jasper
