### ISSUE TITLE
Enabling debug log mode causes exception in push notifications

### ISSUE THREAD

**Issue by thioz** [tig-nl/buckaroo-magento2#6]
When enabling file logging, push notifications get an exception which seems to be a DI misconfiguration which leads to the first argument for initializing Monolog being the ObjectManager.

main.CRITICAL: InvalidArgumentException: A stream must either be a resource or a string. in /var/www/mostwanted/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:50
Stack trace:
#0 /var/www/mostwanted/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Monolog\Handler\StreamHandler->__construct(Object(Magento\Framework\ObjectManager\ObjectManager))
#1 /var/www/mostwanted/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Monolog\\Handler...', Array)
#2 /var/www/mostwanted/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Compiled->create('Monolog\\Handler...', Array)
#3 /var/www/mostwanted/vendor/tig/buckaroo/Debug/Debugger.php(299): Magento\Framework\ObjectManager\ObjectManager->create('Monolog\\Handler...', Array)
#4 /var/www/mostwanted/vendor/tig/buckaroo/Debug/Debugger.php(261): TIG\Buckaroo\Debug\Debugger->createStreamHandler('TIG_Buckaroo.lo...')
#5 /var/www/mostwanted/vendor/tig/buckaroo/Model/Refund/Push.php(157): TIG\Buckaroo\Debug\Debugger->log()
#6 /var/www/mostwanted/vendor/tig/buckaroo/Model/Push.php(236): TIG\Buckaroo\Model\Refund\Push->receiveRefundPush(Array, true, Object(Magento\Sales\Model\Order\Interceptor))
#7 [internal function]: TIG\Buckaroo\Model\Push->receivePush()

**Comment by tig-robertgrundeken** [comment]
Thank you for pointing this out.

There is an issue on the backlog issue [BUCKM2-93](https://jira.tig.nl/browse/BUCKM2-93). Workaround is to turn off the logger in the configuration. It prevents the error, but is not a solution.

The actual problem will be solved when this ticket is in the sprint.

**Comment by thioz** [comment]
Thanks for acknowledging the bug ... We already put the workaround into place and it works. 

I think the solution would be to inject an interface into the constructor, adding a preference to the TIG\Buckaroo\Debug\Logger class in the di.xml, so it will actually use the arguments provided in the di.xml for type TIG\Buckaroo\Debug\Logger 

Using the objectmanager to build the logger while trying to inject custom parameters is causing the bug I think.
