### ISSUE TITLE
FireCheckout support

### ISSUE THREAD

**Issue by blueglobeNL** [tig-nl/buckaroo-magento2#60]
## Please follow the guide below

- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like.
- We may ask some questions or ask you to provide addition information after you placed your request.

---

### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento 2 extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG Buckaroo Magento 2 extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If your issue contains security sensitive information
** If your issue may contain sensitive information, please send us an e-mail at security@tig.nl.**
- [x] This issue does not contain any security sensitive information

---

### If the purpose of your issue is a *bug report*
I'm using a Magento 2.2.6 webshop and installed the latest version of FireCheckout and your Buckaroo extension. The FireCheckout extension comes with an option to add custom checkout fields and I've set one up, so customers can leave a comment during checkout.

When I finish my order using the default Magento payment method "banktransfer", the order comment works fine. The comment entered during checkout is saved in the database and presented in the order confirmation email and visible in the backend.

When I use one of the Buckaroo payment methods (for example iDeal) the comment "disappears" during communication with Buckaroo.

**Comment by tig-jaspersmits** [comment]
Hi @blueglobeNL ,

Thanks for your message. Currently there is no support for the FireCheckout. We have in it on our backlog so we will probably add this functionality in the future.

Kind regards,

Jasper
