### ISSUE TITLE
Afterpay 1, 2 and 3 not working

### ISSUE THREAD

**Issue by renehol** [tig-nl/buckaroo-magento2#61]
## Please follow the guide below

- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like.
- We may ask some questions or ask you to provide addition information after you placed your request.

---

### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento 2 extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x ] Bug report (encountered problems with the TIG Buckaroo Magento 2 extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If your issue contains security sensitive information
** If your issue may contain sensitive information, please send us an e-mail at security@tig.nl.**
- [x ] This issue does not contain any security sensitive information

---

### If the purpose of your issue is a *feature request*
- As a *..certain type of user..* I’d like to *..describe what you want..* in order to *..write goal(s)..*
- Suggestions and background: 
  If you have ideas for the solution write them down here. Include images, a picture is more worth than 1,000 words. If none, remove this line.

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
Place product in basket
Checkout with guest of customer
Choose AfterPay
Choose gender
Choose birthday
Place order

Expected result
Order is placed

- Actual result (Please provide screenshots if applicable)
Error is giving:
{
  "message": "Er is een fout opgetreden op de server. Probeer de bestelling opnieuw te plaatsen.",

"trace": "#0 \vendor\magento\framework\Interception\Interceptor.php(58): Magento\\Checkout\\Model\\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder('{{key}}...', '{{email}}...'
Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor)
Object(Magento\\Quote\\Model\\Quote\\Address\\Interceptor))\n#1 \vendor\magento\framework\Interception\Interceptor.php(138): TIG\\Buckaroo\\Model\\GuestPaymentInformationManagement\\Interceptor->___callParent('savePaymentInfo...'
Array)\n#2 \vendor\magento\framework\Interception\Interceptor.php(153): TIG\\Buckaroo\\Model\\GuestPaymentInformationManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}('{{key}}...'
'{{email}}...'
Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor)
Object(Magento\\Quote\\Model\\Quote\\Address\\Interceptor))\n#3 \generated\code\TIG\Buckaroo\Model\GuestPaymentInformationManagement\Interceptor.php(65): TIG\\Buckaroo\\Model\\GuestPaymentInformationManagement\\Interceptor->___callPlugins('savePaymentInfo...'
Array
Array)\n#4 \vendor\tig\buckaroo\Model\GuestPaymentInformationManagement.php(115): TIG\\Buckaroo\\Model\\GuestPaymentInformationManagement\\Interceptor->savePaymentInformationAndPlaceOrder('{{key}}...'
'{{email}}...'
Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor)
Object(Magento\\Quote\\Model\\Quote\\Address\\Interceptor))\n#5 \generated\code\TIG\Buckaroo\Model\GuestPaymentInformationManagement\Interceptor.php(24): TIG\\Buckaroo\\Model\\GuestPaymentInformationManagement->buckarooSavePaymentInformationAndPlaceOrder('{{key}}...'
'{{email}}...'
Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor)
Object(Magento\\Quote\\Model\\Quote\\Address\\Interceptor))\n#6 [internal function]: TIG\\Buckaroo\\Model\\GuestPaymentInformationManagement\\Interceptor->buckarooSavePaymentInformationAndPlaceOrder('{{key}}...'
'{{email}}...'
Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor)
Object(Magento\\Quote\\Model\\Quote\\Address\\Interceptor))\n#7 \vendor\magento\module-webapi\Controller\Rest\SynchronousRequestProcessor.php(95): call_user_func_array(Array
Array)\n#8 \vendor\magento\module-webapi\Controller\Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#9 \vendor\magento\framework\Interception\Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \vendor\magento\framework\Interception\Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch'
Array)\n#11 \vendor\magento\framework\Interception\Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#12 \generated\code\Magento\Webapi\Controller\Rest\Interceptor.php(26): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch'
Array
Array)\n#13 \vendor\magento\framework\App\Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#14 \generated\code\Magento\Framework\App\Http\Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#15 \vendor\magento\framework\App\Bootstrap.php(258): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#16 \pub\index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#17 \Users\{{usr}}\.composer\vendor\weprovide\valet-plus\server.php(131): require('\Users\{{usr}}\Php...')\n#18 {main}",
}

- Workaround (If available, otherwise just write "None")
None

### If the purpose of your issue is about anything else, please describe your issue here
- Explain your issue here

### TIG support

- Please ask your question in English to ensure that your issue can help other people internationally. Nevertheless we will respond in English.

**Comment by tig-jaspersmits** [comment]
Hi @renehol ,

Thanks for contacting us. I've just tried to reproduce this problem, but I'm not running into any problems and I can correctly place an Afterpay order without that error showing up. Seems like it might be environment related. You could contact Buckaroo and submit a support request through mail on support@buckaroo.nl or call Buckaroo on phone number 030-711 5000.

Kind regards,

Jasper
