### ISSUE TITLE
Support for Magento 2.3.2

### ISSUE THREAD

**Issue by carlocarels** [tig-nl/buckaroo-magento2#63]
## Please follow the guide below

- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like.
- We may ask some questions or ask you to provide addition information after you placed your request.

---

### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento 2 extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [ ] Bug report (encountered problems with the TIG Buckaroo Magento 2 extension)
- [ ] Extension support request (request for adding support for a new extension)
- [x] Other

---

### If your issue contains security sensitive information
** If your issue may contain sensitive information, please send us an e-mail at security@tig.nl.**
- [x] This issue does not contain any security sensitive information

---

- Please ask your question in English to ensure that your issue can help other people internationally. Nevertheless we will respond in English.

**Magento released a update for Magento 2.3.2. Can you create a new release for this as soon as possible?**

**Comment by igorwulff** [comment]
Hi TIG, I understand 2.3.2 needs to be tested, but can at least a RC be provided just like previous times?

**Comment by maartenwolfsen** [comment]
Also, is there any information about when this will be tested?

**Comment by joost-florijn-kega** [comment]
@tig-robertgrundeken When do you expect that the final version will be released?

**Comment by carlocarels** [comment]
> @tig-robertgrundeken When do you expect that the final version will be released?

I'm curious too!

**Comment by trebb0r** [comment]
> > @tig-robertgrundeken When do you expect that the final version will be released?
> 
> I'm curious too!

I'm curious too! :)

**Comment by tig-robertgrundeken** [comment]
Hi All,
Thank you all for the notices. We finished internal testing. Expectation is to have a stable release within two weeks.

**Comment by trebb0r** [comment]
It's been almost three weeks now, dare to ask for an update? ;)

**Comment by tig-robertgrundeken** [comment]
@trebb0r You can always ask! Buckaroo is checking release at this moment. The intention is to release this week a stable version.

**Comment by tig-robertgrundeken** [comment]
Hi All, It's here. A combined release with new payment method Apple Pay and support for 2.3.2 and 2.2.9:
https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.11.0
