### ISSUE TITLE
[Bug] cannot configure payment module

### ISSUE THREAD

**Issue by reense** [tig-nl/buckaroo-magento2#64]
## Please follow the guide below

- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like.
- We may ask some questions or ask you to provide addition information after you placed your request.

---

### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento 2 extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG Buckaroo Magento 2 extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If your issue contains security sensitive information
** If your issue may contain sensitive information, please send us an e-mail at security@tig.nl.**
- [x] This issue does not contain any security sensitive information
Hi guys,

When I install the latest version of the module (1.11.0) on a shop i'm working on (Magento 2.3.2) I cannot  make any changes to the settings (under Stores > configuration > Sales > Payment methods). I have enabled the module and put it in test modus, as the docs described. The configure button has a class  "disabled" on it. When I remove this this class, I am able to make changes to the Buckaroo settings. 
This is what I see:
![Screenshot 2019-08-14 at 16 08 26](https://user-images.githubusercontent.com/3921273/63027779-dabdc400-bead-11e9-9836-c9af8f5620d8.png)

I've done some minor debugging on this issue, and found that the disabled class is added by the function `_isPaymentEnabled()` in file `Block/Adminhtml/System/Config/Fieldset/Payment.php`. This function tries to loop through the `activity_path` on the `$groupConfig` array. This field is, however, not set on this array.

There is a `path` key on the `$groupConfig` array, however, this does only contain the string `payment`. 

There is also a `children` key in the array, which contains the payment methods. These do contain a `path` key where we can see a valid config path.

![image](https://user-images.githubusercontent.com/3921273/63028212-aac2f080-beae-11e9-9078-c7e8c8f4501b.png)

My question is, am I missing something which causes there to be no `activity_path` key on my `$groupConfig` array? Or is the module simply not fully compatible with Magento 2.3.2? 

---

### TIG support

- Please ask your question in English to ensure that your issue can help other people internationally. Nevertheless we will respond in English.

**Comment by tig-jaspersmits** [comment]
@reense ,

Thanks for contacting us. I've just tried to reproduce this. But I was unable to do so. I installed Buckaroo M2 v1.11.0 on a clean Magento 2.3.2 environment. The button you are talking about is clickable. See: https://www.screencast.com/t/LDDlqphhkp8Z

Maybe you are using another extension which impacts the button for some reason. Is it possible to test without any other extension besides Buckaroo enabled?

Kind regards,

Jasper

**Comment by reense** [comment]
@tig-jaspersmits hmm strange! I will disable all custom modules to see if that makes any change.

**Comment by reense** [comment]
@tig-jaspersmits After some debugging I've found the problem: I needed to enable Magento_Paypal. By default, we disable this module (and it's dependencies Magento_InstantPurchase & Magento_Vault). When I enabled these, the configure button started to work! 

Very strange, maybe this is a nice addition to the FAQ?

**Comment by tig-jaspersmits** [comment]
Hi @reense ,

Thanks for letting me know! I'll double check that and I will put up a knowledge base article.

Kind regards,

Jasper

**Comment by tig-jaspersmits** [comment]
The article can be found here: https://confluence.tig.nl/x/qYA-B

**Comment by reense** [comment]
@tig-jaspersmits Thank you!
