### ISSUE TITLE
Invoice create issue with paypal accounts containing + character in e-mail address

### ISSUE THREAD

**Issue by esseremmerik** [tig-nl/buckaroo-magento2#65]
- [X] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento 2 extension.

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [X] Bug report (encountered problems with the TIG Buckaroo Magento 2 extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If your issue contains security sensitive information
** If your issue may contain sensitive information, please send us an e-mail at security@tig.nl.**
- [X] This issue does not contain any security sensitive information

---

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
- When an order is placed using paypal and the customer uses a + in the e-mail address, the invoice is not created in Magento. This also happens when a credit is created from the plaza

**Comment by tig-jaspersmits** [comment]
Hi @esseremmerik ,

Thanks for your bug report. I've just tested this and I'm unable to reproduce the problem. When I use an e-mailaddress like this: jasper+21@tig.nl and finish an order, there is an invoice created in Magento. When I refund this through the Buckaroo Plaza, I get a creditmemo as well.

It might be an environment specific problem. I recommend contacting Buckaroo about this. You can contact them on support@buckaroo.nl or call Buckaroo on phone number 030-711 5000.

Kind regards,

Jasper

**Comment by tig-jaspersmits** [comment]
This relates to this ticket: https://github.com/tig-nl/buckaroo-magento2/issues/55
