### ISSUE TITLE
Unable to update to Magento 2.3.2-p2

### ISSUE THREAD

**Issue by igorwulff** [tig-nl/buckaroo-magento2#67]
Hello Tig,

Magento provided an recent patch update to version 2.3.2-p1 and 2.3.2-p2. Currently we are unable to update our Magento shops and make sure they are up to date with the latest security updates.

Can magento/framework be changed to include 102.0.2-p1 and 102.0.2-p2?

We require this change as soon as possible.

**Comment by tig-robertgrundeken** [comment]
Hi @igorwulff  
We released a RC with support of 2.3.2-p2, 2.3.3 and 2.2.10. Also PHP 7.3 is added to composer.
https://github.com/tig-nl/buckaroo-magento2/releases/tag/v1.13.0-RC1
