### ISSUE TITLE
Issue with Magento 2.3.3

### ISSUE THREAD

**Issue by JoostWan** [tig-nl/buckaroo-magento2#69]
Version Magento 2 module Buckaroo: 1.14.0
Magento 2.3.3

After placed a order there is a redirect to the webshop. It generates the next error: 

`[25-Nov-2019 15:20:05 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Framework\Mail\AddressConverter::convertMany() must be of the type array, null given, called in /Users/username/Sites/site/vendor/magento/framework/Mail/Template/TransportBuilder.php on line 426 and defined in /Users/username/Sites/site/vendor/magento/framework/Mail/AddressConverter.php:59
Stack trace:
#0 /Users/username/Sites/site/vendor/magento/framework/Mail/Template/TransportBuilder.php(426): Magento\Framework\Mail\AddressConverter->convertMany(NULL)
#1 /Users/username/Sites/site/vendor/magento/framework/Mail/Template/TransportBuilder.php(202): Magento\Framework\Mail\Template\TransportBuilder->addAddressByType('to', NULL, 'Firstname Lastname')
#2 /Users/username/Sites/site/generated/code/Magento/Framework/Mail/Template/TransportBuilder/Interceptor.php(37): Magento\Framework\Mail\Template\TransportBuilder->addTo(NULL, 'Firstname Lastname')
#3 /Users/username/Sites/site/vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php(63): Magento\Framework\Mail\Template\Trans in /Users/username/Sites/site/vendor/magento/framework/Mail/AddressConverter.php on line 59`

**Comment by tig-jaspersmits** [comment]
Hi @JoostWan ,

Thanks for letting us know. We will take a look at it and let you know if we are able to reproduce this. When I have more information I'll let you know.

Kind regards,
Jasper

**Comment by tig-jaspersmits** [comment]
@JoostWan ,

My colleague has tested this, but was unable to reproduce it.
Are you using a clean Magento environment?

Kind regards,
Jasper

**Comment by JoostWan** [comment]
@tig-jaspersmits Sorry, had a other module that was the error.

**Comment by tig-jaspersmits** [comment]
@JoostWan thanks fore letting us know!
