### ISSUE TITLE
Magento 2.3.3-p1 & 2.3.4 compatability

### ISSUE THREAD

**Issue by stoopman** [tig-nl/buckaroo-magento2#72]
Currently the buckaroo package has a requirement of magento/framework[102.0.3-p1].
Could you add 102.0.3-p2 for the recently released security patch?

Thanks!

**Comment by tig-jaspersmits** [comment]
Hi @stoopman ,

Thanks for your message. Please contact Buckaroo support about any questions regarding the Buckaroo Magento 2 extension. They can be reached on support@buckaroo.nl or +31307115000. At the start of this year they have been doing the support themselves.

Kind regards,
Jasper
TIG
